// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: Catalog.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ViewCatalogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatalogType string `protobuf:"bytes,1,opt,name=catalog_type,json=catalogType,proto3" json:"catalog_type,omitempty"`
}

func (x *ViewCatalogRequest) Reset() {
	*x = ViewCatalogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Catalog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewCatalogRequest) ProtoMessage() {}

func (x *ViewCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Catalog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewCatalogRequest.ProtoReflect.Descriptor instead.
func (*ViewCatalogRequest) Descriptor() ([]byte, []int) {
	return file_Catalog_proto_rawDescGZIP(), []int{0}
}

func (x *ViewCatalogRequest) GetCatalogType() string {
	if x != nil {
		return x.CatalogType
	}
	return ""
}

type ViewCatalogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	JsonString string `protobuf:"bytes,2,opt,name=json_string,json=jsonString,proto3" json:"json_string,omitempty"`
}

func (x *ViewCatalogResponse) Reset() {
	*x = ViewCatalogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Catalog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewCatalogResponse) ProtoMessage() {}

func (x *ViewCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Catalog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewCatalogResponse.ProtoReflect.Descriptor instead.
func (*ViewCatalogResponse) Descriptor() ([]byte, []int) {
	return file_Catalog_proto_rawDescGZIP(), []int{1}
}

func (x *ViewCatalogResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ViewCatalogResponse) GetJsonString() string {
	if x != nil {
		return x.JsonString
	}
	return ""
}

var File_Catalog_proto protoreflect.FileDescriptor

var file_Catalog_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x22, 0x37, 0x0a, 0x12, 0x56, 0x69, 0x65, 0x77, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f,
	0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61,
	0x74, 0x61, 0x6c, 0x6f, 0x67, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4a, 0x0a, 0x13, 0x56, 0x69, 0x65,
	0x77, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6a, 0x73, 0x6f, 0x6e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x32, 0x63, 0x0a, 0x0e, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x23, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x43, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Catalog_proto_rawDescOnce sync.Once
	file_Catalog_proto_rawDescData = file_Catalog_proto_rawDesc
)

func file_Catalog_proto_rawDescGZIP() []byte {
	file_Catalog_proto_rawDescOnce.Do(func() {
		file_Catalog_proto_rawDescData = protoimpl.X.CompressGZIP(file_Catalog_proto_rawDescData)
	})
	return file_Catalog_proto_rawDescData
}

var file_Catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Catalog_proto_goTypes = []interface{}{
	(*ViewCatalogRequest)(nil),  // 0: shop.service.v1.ViewCatalogRequest
	(*ViewCatalogResponse)(nil), // 1: shop.service.v1.ViewCatalogResponse
}
var file_Catalog_proto_depIdxs = []int32{
	0, // 0: shop.service.v1.CatalogService.List:input_type -> shop.service.v1.ViewCatalogRequest
	1, // 1: shop.service.v1.CatalogService.List:output_type -> shop.service.v1.ViewCatalogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Catalog_proto_init() }
func file_Catalog_proto_init() {
	if File_Catalog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Catalog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewCatalogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Catalog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewCatalogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Catalog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Catalog_proto_goTypes,
		DependencyIndexes: file_Catalog_proto_depIdxs,
		MessageInfos:      file_Catalog_proto_msgTypes,
	}.Build()
	File_Catalog_proto = out.File
	file_Catalog_proto_rawDesc = nil
	file_Catalog_proto_goTypes = nil
	file_Catalog_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatalogServiceClient interface {
	List(ctx context.Context, in *ViewCatalogRequest, opts ...grpc.CallOption) (*ViewCatalogResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) List(ctx context.Context, in *ViewCatalogRequest, opts ...grpc.CallOption) (*ViewCatalogResponse, error) {
	out := new(ViewCatalogResponse)
	err := c.cc.Invoke(ctx, "/shop.service.v1.CatalogService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
type CatalogServiceServer interface {
	List(context.Context, *ViewCatalogRequest) (*ViewCatalogResponse, error)
}

// UnimplementedCatalogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCatalogServiceServer struct {
}

func (*UnimplementedCatalogServiceServer) List(context.Context, *ViewCatalogRequest) (*ViewCatalogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterCatalogServiceServer(s *grpc.Server, srv CatalogServiceServer) {
	s.RegisterService(&_CatalogService_serviceDesc, srv)
}

func _CatalogService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shop.service.v1.CatalogService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).List(ctx, req.(*ViewCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CatalogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shop.service.v1.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _CatalogService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Catalog.proto",
}
